- name: Make sure keyring is present and current
  pacman:
    name: archlinux-keyring
    state: latest
    update_cache: yes
  become: yes

- name: Install reflector to update mirrorlist
  pacman:
    name:
      - reflector
  become: yes

- name: update mirrorlist
  shell:
    cmd: reflector -c DE -c CH -c AT -l 20 --fastest 10 --save /etc/pacman.d/mirrorlist
  become: yes

- name:  update pacman (pacman -Syu)
  pacman:
    update_cache: yes
    upgrade: yes
  become: yes

- include_vars: packages.yml

- name: Install base
  pacman:
    name: "{{ packages }}"
    state: present
  become: yes

# this does not work behind a proxy, reqwest does not seem to pickup the env correctly
# - name: install rust by rustup
#   shell: curl https://sh.rustup.rs -sSf | sh -s -- -y
#   args:
#     warn: false

- name: install starship prompt
  shell: cargo install starship

- name: remove bashrc prior to stowing
  file:
    path: "{{ user_home }}/.bashrc"
    state: absent

- name: remove bash_profile prior to stowing
  file:
    path: "{{ user_home }}/.bash_profile"
    state: absent

- name: create .local/bin to prevent stow from "owning" it
  file:
    path: "{{ user_home }}/.local/bin"
    state: directory
    mode: '0750'

- name: Clone homestow
  git:
    repo: "{{ homestow_repo_url }}"
    version: master
    dest: "{{ stow_dir }}"
    accept_hostkey: yes

- name: stow base
  shell:
    cmd: stow git nvim aliases bash fish rust
    chdir: "{{ stow_dir }}"

