- include_vars: packages.yml

- name: install python
  pacman:
    name: "{{ packages }}"
  become: yes

- name: install poetry
  shell: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  args:
    warn: false

