- name: Add user to sudoers
  lineinfile:
    path: "/etc/sudoers.d/{{ user }}"
    line: "{{ user }} ALL=(ALL) ALL"
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'
  become: yes

- name: Set authorized key taken from file
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', '/home/bab1imb/.ssh/id_rsa.pub') }}"
  become: yes
  become_user: "{{ user }}"

